server:
  port: 8090

spring:
  application:
    name: authorization-application

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/oauth2_jwt?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: MySql2019!
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    show-sql: true

security:
  oauth2:
    resource:
      id: teste-id

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      dafaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
